services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    # ports will not be exposed directly, accessed by NGINX
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_NGINX
    ports:
      - "80:80"
    depends_on:
      - app