name: Build and Publish Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  publish_images:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}
        
      - name: Docker Buildx app
        uses: docker/build-push-action@v6
        with:
          context: ./app
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/darshan:latest
          push: true
        
      - name: Docker Buildx NGNIX
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile_NGINX
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/nginx:latest
          push: true
