name: Deploy to Azure Container Apps
on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    environment: Production 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        
      - name: Docker Buildx app
        uses: docker/build-push-action@v6
        with:
          context: ./app
          tags: ${{ vars.ACR_LOGIN_SERVER }}/darshan:${{github.sha}}
          push: true
        
      - name: Docker Buildx NGNIX
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile_NGINX
          tags: ${{ vars.ACR_LOGIN_SERVER }}/nginx:${{github.sha}}
          push: true
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1

